### ISSUE TITLE
Why you didn't use my api? 

### ISSUE THREAD

**Issue by ShadabAlam786** [bots-business/bbapp-translations#1]
**Api Url:** https://shadabalam.cf/api/translator.php

This Command Is For Sending Request To Api For Translating The Text.

📎 Command: /Translate 

🔊 Answer: Enter Your Text To Convert It To Another Language. 

📩 Wait For Answer: On

🔎 BJS: HTTP.get({
url: "https://shadabalam.cf/api/translator.php",
params: { "text": message, "language": "hi" },

success: "Translated" })

After That Make Second Command For Getting Results:

📎 Command: Translated 

🔎 BJS: var result = JSON.parse(content)
var text = result.data.translations[0].translatedText
var detected = result.data.translations[0].detectedSourceLanguage
Bot.sendMessage("*🎉 Text Converted From "+detected+" To Hi.\n\n📑 Translated Text: "+text+"\n\n🔊 Language: "+detected+" (Auto Detected)*")

It Supports Over 200+ Languages: https://telegra.ph/Api-Documentation-Of-Translator-11-30 ( Check All Supported Language Code Here )

**Comment by bots-business** [comment]
We need quality fluent translation. Not automatic

**Comment by ShadabAlam786** [comment]
Lol, Jab Ghee Sidhi Ungli Se Nikal Raha Hai Toh Tumhe Pasand Hi Nhi Toh Nikalo Ghee Ungli Tdehi Karke Mujhe Kya 🤷‍♂
